import { Theme } from '../../../../../../../../src/lib/utils/theme';
export declare const padding: (theme: Theme) => string;
export declare const margin: (theme: Theme) => string;
export declare const border: (theme: Theme) => string;
export declare const borderRadius: (theme: Theme) => string;
export declare const borderColor: (theme: Theme) => string;
export declare const fontSize: (theme: Theme) => string;
export declare const fontColor: (theme: Theme) => string;
export declare const fontColorActive: (theme: Theme) => string;
export declare const fontWeightLight: (theme: Theme) => number;
export declare const fontWeightNormal: (theme: Theme) => number;
export declare const fontWeightSemiBold: (theme: Theme) => number;
export declare const fontWeightBold: (theme: Theme) => number;
export declare const iconSize: (theme: Theme) => string;
export declare const iconColor: (theme: Theme) => string;
export declare const iconColorActive: (theme: Theme) => string;
export declare const backgroundColor: (theme: Theme) => string;
export declare const backgroundColorSelected: (theme: Theme) => string;
export declare const backgroundColorActive: (theme: Theme) => string;
export declare const backgroundColorHover: (theme: Theme) => string;
export declare const backgroundColorFocused: (theme: Theme) => string;
export declare const backgroundColorDisabled: (theme: Theme) => string;
export declare const boxShadow: (theme: Theme) => string;
export declare const boxShadowHover: (theme: Theme) => string;
export declare const blue50: (theme: Theme) => string;
export declare const blue100: (theme: Theme) => string;
export declare const blue200: (theme: Theme) => string;
export declare const blue300: (theme: Theme) => string;
export declare const blue400: (theme: Theme) => string;
export declare const blue500: (theme: Theme) => string;
export declare const blue600: (theme: Theme) => string;
export declare const blue700: (theme: Theme) => string;
export declare const blue800: (theme: Theme) => string;
export declare const blue900: (theme: Theme) => string;
export declare const gray50: (theme: Theme) => string;
export declare const gray100: (theme: Theme) => string;
export declare const gray200: (theme: Theme) => string;
export declare const gray300: (theme: Theme) => string;
export declare const gray400: (theme: Theme) => string;
export declare const gray500: (theme: Theme) => string;
export declare const gray600: (theme: Theme) => string;
export declare const gray700: (theme: Theme) => string;
export declare const gray800: (theme: Theme) => string;
export declare const gray900: (theme: Theme) => string;
export declare const teal: (theme: Theme) => string;
export declare const red: (theme: Theme) => string;
export declare const orange: (theme: Theme) => string;
export declare const amber: (theme: Theme) => string;
export declare const green: (theme: Theme) => string;
export declare const cyan: (theme: Theme) => string;
export declare const blueLight: (theme: Theme) => string;
export declare const blue: (theme: Theme) => string;
export declare const violet: (theme: Theme) => string;
export declare const magenta: (theme: Theme) => string;
export declare const pink: (theme: Theme) => string;
export declare const brown: (theme: Theme) => string;
export declare const gray: (theme: Theme) => string;
export declare const white: (theme: Theme) => string;
export declare const black: (theme: Theme) => string;
export declare const error: (theme: Theme) => string;
export declare const primaryColor: (theme: Theme) => string;
export declare const primaryColorSvg: (theme: Theme) => string;
export declare const successColor: (theme: Theme) => string;
export declare const warningColor: (theme: Theme) => string;
export declare const errorColor: (theme: Theme) => string;
export declare const infoColor: (theme: Theme) => string;
export declare const componentHeight: (theme: Theme) => string;
export declare const alertMessageFontSize: (theme: Theme) => string;
export declare const alertDescriptionMessageFontSize: (theme: Theme) => string;
export declare const headingFontSize: (theme: Theme) => {
    h1: string;
    h2: string;
    h3: string;
    h4: string;
    h5: string;
    h6: string;
};
export declare const buttonSize: (theme: Theme) => {
    small: {
        paddingX: string;
        fontSize: string;
        height: string;
    };
    medium: {
        paddingX: string;
        fontSize: string;
        height: string;
    };
    large: {
        paddingX: string;
        fontSize: string;
        height: string;
    };
    xlarge: {
        paddingX: string;
        fontSize: string;
        height: string;
    };
};
export declare const dataPickerHeight: (theme: Theme) => string;
export declare const dataPickerFontSize: (theme: Theme) => string;
export declare const dataPickerPaddingX: (theme: Theme) => string;
export declare const paginationHeight: (theme: Theme) => string;
export declare const paginationFontSize: (theme: Theme) => string;
export declare const paginationPaddingX: (theme: Theme) => string;
export declare const paragraphSize: (theme: Theme) => {
    small: {
        fontSize: string;
        lineHeight: string;
    };
    medium: {
        fontSize: string;
        lineHeight: string;
    };
    large: {
        fontSize: string;
        lineHeight: string;
    };
    xlarge: {
        fontSize: string;
        lineHeight: string;
    };
};
export declare const tableFontSize: (theme: Theme) => string;
export declare const tagLineHeight: (theme: Theme) => string;
export declare const tagFontSize: (theme: Theme) => string;
export declare const tagPaddingX: (theme: Theme) => string;
export declare const tagPaddingY: (theme: Theme) => string;
export declare const tabHeight: (theme: Theme) => string;
export declare const tabFontSize: (theme: Theme) => string;
export declare const tabPaddingX: (theme: Theme) => string;
export declare const inputHeight: (theme: Theme) => string;
export declare const inputFontSize: (theme: Theme) => string;
export declare const inputPaddingX: (theme: Theme) => string;
export declare const selectHeight: (theme: Theme) => string;
export declare const selectFontSize: (theme: Theme) => string;
export declare const selectPaddingX: (theme: Theme) => string;
export declare const cardPaddingX: (theme: Theme) => string;
export declare const cardPaddingY: (theme: Theme) => string;
export declare const cardFontSize: (theme: Theme) => string;
export declare const cardLineHeight: (theme: Theme) => string;
export declare const switchPeriodComparativeFontSize: (theme: Theme) => string;
export declare const gridOuterPadding: (theme: Theme) => string;
export declare const gridOuterMargin: (theme: Theme) => string;
export declare const gridGutterWidth: (theme: Theme) => string;
export declare const gridGutterCompensation: (theme: Theme) => string;
export declare const gridHalfGutterWidth: (theme: Theme) => string;
export declare const gridBreakpoints: (theme: Theme) => {
    xs: string;
    sm: string;
    md: string;
    lg: string;
};
export declare const gridColumns: (theme: Theme) => number;
export declare const gridContainerSm: (theme: Theme) => string;
export declare const gridContainerMd: (theme: Theme) => string;
export declare const gridContainerLg: (theme: Theme) => string;
export declare const progressHeight: (theme: Theme) => string;
export declare const progressFontSize: (theme: Theme) => string;
export declare const progressBackgroundColor: (theme: Theme) => string;
export declare const formControlMessageFontSize: (theme: Theme) => string;
